-- Each new term in the Fibonacci sequence is generated by adding the previous two
-- terms. By starting with 1 and 2, the first 10 terms will be:
-- 
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- 
-- By considering the terms in the Fibonacci sequence whose values do not exceed
-- four million, find the sum of the even-valued terms.

local max = 4000000
local a, b = 1, 1
local sum = 0

while b < max do
    if b%2 == 0 then
        sum = sum + b
    end

    a, b = b, a + b -- lua can do this, pretty awesome :)
end

print(sum)
