-- Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten
-- pentagonal numbers are:
--
-- 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
--
-- It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70
-- − 22 = 48, is not pentagonal.
--
-- Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
-- difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of
-- D?

PENTAGONS = {}

function p(n)
    local val = n * (3*n - 1) / 2
    
    -- if not PENTAGONS[val] then
    --     print("pn:", n , "val:",val)
    --     PENTAGONS[val] = 1
    -- end

    return val
end


function main()
    --populate pentagons with a big number
    for i = 1, 1000000 do
        PENTAGONS[p(i)] = 1
    end

    -- arbitrary big number
    local minD = 10000000

    for a = 1, 10000 do
        local b = a + 1
        while p(b) - p(a) < minD do
            local sum = p(a) + p(b)
            local diff = p(b) - p(a)

            if PENTAGONS[sum] and PENTAGONS[diff] then
                minD = diff
            end

            b = b + 1
        end
    end

    print(minD)
end

main()
