-- Triangle, pentagonal, and hexagonal numbers are generated by the following
-- formulae:
-- Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
-- Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
-- Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...
--
-- It can be verified that T285 = P165 = H143 = 40755.
--
-- Find the next triangle number that is also pentagonal and hexagonal.

TRI, PENT, HEX = {}, {}, {}

function t(n)
    return n*(n+1)/2
end


function p(n)
    return n*(3*n - 1)/2
end


function h(n)
    return n*(2*n - 1)
end


function populate(n)
    TRI[t(n)], PENT[p(n)], HEX[h(n)] = 1, 1, 1
end


function main()
    for i=1,100000 do
        populate(i)
    end

    local i = 286
    while true do
        local v = t(i)
        if PENT[v] and HEX[v] then
            break
        end
        i = i + 1
    end

    print(t(i))
end

main()
